### ISSUE TITLE
Tech debt/backporting tracker

### ISSUE THREAD

**Issue by tumido** [AICoE/meteor#90]
Umbrella issue for tech debt and backporting:

- [x] Remove deployment logic from the operator and move it to a tekton pipeline
- [ ] Backport `.aicoe.yaml` analysis to notebook pipeline in AICoE
- [ ] Backport restructuring changes to AICoE pipelines from meteor

**Comment by tumido** [comment]
cc @goern

**Comment by tumido** [comment]
Consider converging AICoE-CI and changes from meteor in a tekton catalog bundle image.

https://tekton.dev/docs/pipelines/pipelines/#tekton-bundles

**Comment by tumido** [comment]
Related: https://github.com/thoth-station/helm-charts/issues/7

**Comment by tumido** [comment]
Installing this via OpenShift fails on `0.1.0` version of the Helm chart due to:

```
Release "meteor-pipelines" failed: admission webhook "validation.webhook.pipeline.tekton.dev" denied the request: validation failed: invalid value: repo-items-recheck: spec.steps[4].name
```

![image](https://user-images.githubusercontent.com/7453394/141362013-6896a53f-da31-4b6e-be8a-2b1aa0d360e6.png)

This will be probably fixed in `0.2.0` but that release is missng from listing (see comment above)
